---
- name: copy package
  copy:
    src: "nginx-passenger/nginx-passenger-1.6.1-1-{{ pacman_architecture }}.pkg.tar.xz"
    dest: /root
    owner: root
    group: root
    mode: "0644"
  register: nginx_copy_package

- name: install
  pacman:
    name: "/root/nginx-passenger-1.6.1-1-{{ pacman_architecture }}.pkg.tar.xz"
    state: present
  when: nginx_copy_package.changed
