---
- include: install.yml

- name: create main configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: nginx.restart

- name: create configuration directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: "0755"
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: create site configuration files
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ item['_filename'] }}.conf"
  with_items: nginx_sites
  notify: nginx.reload

- name: create symlinks for enabled sites
  file:
    src: "/etc/nginx/sites-available/{{ item['_filename'] }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item['_filename'] }}.conf"
    state: link
    owner: root
    group: root
    mode: "0644"
    force: true
  with_items: nginx_sites
  when: item._enabled
  notify: nginx.reload

- name: start and enable
  service:
    name: nginx
    state: started
    enabled: true
