---
- include: install.yml

- name: create main configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: nginx.restart

- name: create configuration directories
  file:
    path: /etc/nginx/conf.d
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: create site configuration files
  template:
    src: site.j2
    dest: "/etc/nginx/conf.d/{{ item['server']['file_name'] }}.conf"
  with_items: nginx_sites
  when: nginx_sites|lower != 'none'
  notify: nginx.reload

- name: start and enable
  service:
    name: nginx
    state: started
    enabled: true
