---
- hosts: all
  remote_user: root
  vars:
    redmine:
      database: redmine_db
      name: redminer
      pass: redminer
      fulldir: /var/redmine-2.5
      user: "{{ nginx_conf.user }}"
    gollum:
      fulldir: /var/gollum
      user: "{{ nginx_conf.user }}"
    psdash:
      fulldir: /var/psdash-0.4.0
      user: "{{ nginx_conf.user }}"
    postgresql_users:
      - name: "{{ redmine.name }}"
        pass: "{{ redmine.pass }}"
    postgresql_databases:
      - name: "{{ redmine.database }}"
        owner: "{{ redmine.name }}"
    nginx_sites:
      - _filename: default
        _enabled: false
        server:
          server_name: _
          listen:
            - 80 default_server
          return: 444
      - _filename: redmine
        _enabled: true
        server:
          server_name: redmine.example.com
          listen: 80
          root: "{{ redmine.fulldir }}/public"
          location:
            - _name: /
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_enabled: on
      - _filename: gollum
        _enabled: true
        server:
          server_name: gollum.example.com
          listen: 80
          root: "{{ gollum.fulldir }}/public"
          location:
            - _name: /
              root: "{{ gollum.fulldir }}/vendor/bundle/ruby/2.1.0/gems/gollum-3.0.0/lib/gollum/public/gollum/"
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_enabled: on
      - _filename: psdash
        _enabled: true
        server:
          server_name: psdash.example.com
          listen: 80
          root: "{{ psdash.fulldir }}/public"
          location:
            - _name: /
              root: "{{ psdash.fulldir }}/psdash/static"
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_python: "{{ psdash.fulldir }}/bin/python2"
              passenger_enabled: on
  roles:
  - role: base
  - role: nginx
  - role: postgresql
  - role: redmine
  - role: gollum
  - role: psdash
