---
- hosts: all
  remote_user: root
  vars:
    redmine:
      database: redmine_db
      name: redminer
      pass: redminer
      fulldir: /var/redmine-2.5
      user: "{{ nginx_conf.user }}"
    gollum:
      fulldir: /var/gollum
      user: "{{ nginx_conf.user }}"
    psdash:
      fulldir: /var/psdash-0.4.0
      user: "{{ nginx_conf.user }}"
    stringer:
      database: stringer_db
      name: stringerer
      pass: stringerer
      frequency: 8h
      token: iamnotasecret
      fulldir: /var/stringer
      user: "{{ nginx_conf.user }}"
    postgresql_users:
      - name: "{{ redmine.name }}"
        pass: "{{ redmine.pass }}"
      - name: "{{ stringer.name }}"
        pass: "{{ stringer.pass }}"
    postgresql_databases:
      - name: "{{ redmine.database }}"
        owner: "{{ redmine.name }}"
      - name: "{{ stringer.database }}"
        owner: "{{ stringer.name }}"
    nginx_sites:
      - _filename: default
        _enabled: false
        server:
          server_name: _
          listen:
            - 80 default_server
          return: 444
      - _filename: redmine
        _enabled: true
        server:
          server_name: redmine.example.com
          listen: 80
          root: "{{ redmine.fulldir }}/public"
          location:
            - _name: /
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_enabled: on
      - _filename: gollum
        _enabled: true
        server:
          server_name: gollum.example.com
          listen: 80
          root: "{{ gollum.fulldir }}/public"
          location:
            - _name: /
              root: "{{ gollum.fulldir }}/vendor/bundle/ruby/2.1.0/gems/gollum-3.0.0/lib/gollum/public/gollum"
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_enabled: on
      - _filename: psdash
        _enabled: true
        server:
          server_name: psdash.example.com
          listen: 80
          root: "{{ psdash.fulldir }}/public"
          location:
            - _name: /
              root: "{{ psdash.fulldir }}/lib/python2.7/site-packages/psdash/static"
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_python: "{{ psdash.fulldir }}/bin/python2"
              passenger_enabled: on
              passenger_set_cgi_param:
                - "PYTHON_EGG_CACHE {{ psdash.fulldir }}/tmp"
      - _filename: stringer
        _enabled: true
        server:
          server_name: stringer.example.com
          listen: 80
          root: "{{ stringer.fulldir }}/public"
          location:
            - _name: /
              root: "{{ stringer.fulldir }}/app/public"
              try_files: $uri $uri/index.html @passenger
            - _name: "@passenger"
              passenger_enabled: on
              passenger_set_cgi_param:
                - "STRINGER_DATABASE {{ stringer.database }}"
                - "STRINGER_DATABASE_USERNAME {{ stringer.name }}"
                - "STRINGER_DATABASE_PASSWORD {{ stringer.pass }}"
                - "SECRET_TOKEN {{ stringer.token }}"
  roles:
  - role: base
  - role: nginx
  - role: postgresql
  - role: redmine
  - role: gollum
  - role: psdash
  - role: stringer
