---
- name: pip install
  pip:
    name: psdash
    version: 0.4.0
    state: present
    virtualenv: "{{ psdash.fulldir }}"
    executable: pip2
    virtualenv_command: virtualenv2

- name: set permissions
  file:
    path: "{{ psdash.fulldir }}"
    state: directory
    owner: "{{ psdash.user }}"
    group: "{{ psdash.user }}"
    recurse: true

- name: create directories
  file:
    path: "{{ item }}"
    owner: "{{ psdash.user }}"
    group: "{{ psdash.user }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ psdash.fulldir }}/public"
    - "{{ psdash.fulldir }}/tmp"

- name: copy passenger_wsgi.py
  copy:
    src: passenger_wsgi.py
    dest: "{{ psdash.fulldir }}"
    owner: "{{ psdash.user }}"
    group: "{{ psdash.user }}"
    mode: "0640"
