---
- name: generate locales
  locale_gen: # doesn't work on Arch due to spaces in locale.gen
    name: "{{ locale }}"
    state: present

- name: update locale.conf
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf

- name: create timezone symlink
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    mode: "0644"
    force: true

- name: synchronize hardware clock
  command: hwclock --systohc --utc

- name: install ntpd
  pacman:
    name: ntp
    state: present

- name: start and enable ntpd
  service:
    name: ntpd
    state: started
    enabled: true

- name: install ruby
  pacman:
    name: ruby
    state: present

- name: install bundler
  gem:
    name: bundler
    state: latest
    user_install: false
